### ISSUE TITLE
Clarification on the scope of NO_COLOR

### ISSUE THREAD

**Issue by mpldr** [jcs/no_color#119]
ANSI-Codes can do much more than colours. They can add formatting (underline, bold, blinking, …) and affect the cursor. I have divided it into these categories:

- colour
    - foreground
    - background
- formatting
    - bold
    - italic
    - strikethrough
    - …
- movement
    - up/down/left/right
    - save/restore cursor position
- clearing
    - screen
    - line
    - left/right of cursor

In my application of this standard, I took the name literally and only disabled the first category. I this desired behaviour, or are formatting instructions also covered by NO_COLOR? (I would not disable functional codes like movement and clearing)

**Comment by jcs** [comment]
It is strictly about color.  From the website:

> All command-line software which outputs text with ANSI color added should check for the presence of a NO_COLOR environment variable that, when present (regardless of its value), prevents the addition of ANSI color.

Most curses/"TUI" software would be pretty useless without the ability to do cursor positioning with ANSI escape codes.
