### ISSUE TITLE
Guidance around non-color ANSI formatting escapes?

### ISSUE THREAD

**Issue by woodruffw** [jcs/no_color#202]
First, thanks for writing and maintaining this spec. I think it's great, and I try to make all of my tools compatible with it.

This question is a partial dupe of #119, which (IMO) you correctly closed because the scope was too broad.

Instead, I'll narrow it a bit: should `NO_COLOR` also include the basic non-color formatting escapes, like bold/italic/underline/dim/bright?

My intuition is that it should: some terminals with limited support for these escapes will interpret them as colors instead. Similarly, users who expect `NO_COLOR` to produce something clean for `less` or another common pipe destination might find it surprising that they're not included.

See https://github.com/Textualize/rich/issues/2549 for an example of this.

**Comment by jcs** [comment]
I personally use bold in various tools and programs, even with `NO_COLOR` set.  I didn't intend the spec to act like `env TERM=dumb` where it strips all ANSI escape codes, just color.

**Comment by woodruffw** [comment]
Thanks for clarifying that! In that case my expectations were incorrect, so I'm closing this.
