### ISSUE TITLE
FAQ: unclear "doesn't by default does not"

### ISSUE THREAD

**Issue by hugovk** [jcs/no_color#216]
The last paragraph of the FAQ is a little unclear:

> 2. **How should configuration files and command-line arguments be processed
> in the presence of `$NO_COLOR`?**
> 
> 	User-level configuration files and per-instance command-line arguments
> 	should override `$NO_COLOR`.
> 	A user should be able to export `$NO_COLOR` in their shell configuration
> 	file as a default, but configure a specific program in its configuration
> 	file to specifically enable color.
> 
> 	This also means that software that *can* add color but doesn't by default
> 	does not need to care about `$NO_COLOR`, because it will only ever be
> 	adding color when instructed to do so (as it should be).

"... *can* add color but doesn't by default does not need to care ..."

Should one of "doesn't" and "does not" be deleted?

**Comment by jcs** [comment]
No, if the software doesn't output color by default then setting `NO_COLOR` doesn't matter.
