### ISSUE TITLE
Use 0 to disable?

### ISSUE THREAD

**Issue by Slackadays** [jcs/no_color#227]
I have NO_COLOR in my software and it works perfectly as it is right now. However, I was thinking that the standard should include 0 as a valid value to disable the variable and anything else to enable it. This would help make the intent more clear (0 or blank for false, 1 or "true" or "yes" or something else for true) and shouldn't be too difficult to implement. Does this have potential?

**Comment by jcs** [comment]
It's too late to change the spec at this point

**Comment by Slackadays** [comment]
@jcs I find this kind of ironic because the further along something is, the more sense it makes to make versions of the spec that have concrete requirements and changes, and actually someone else had a similar idea in #193
