### ISSUE TITLE
Collaborate with CLICOLOR(_FORCE)

### ISSUE THREAD

**Issue by jhasse** [jcs/no_color#28]
Hi!

A few years ago I've created a similar site, because I was sick of all the different environment variables / command line switches used to control colored output: https://bixense.com/clicolors/

My focus was more on providing a way to *force* colored output, which is useful for CI logs and stuff like that.

Anyway: I think the less standards / variable names the better, what do you think about collaborating? On my site it's currently suggested to turn colors off when `CLICOLOR=0`. I can change that to `NO_COLOR` or even just redirect to your site (if you'd add a section about how to force colors with e.g. `CLICOLOR_FORCE=1`). What do you think?

**Comment by jcs** [comment]
It doesn't look like `CLICOLOR` gained much traction but I agree that fewer environment variables to set and check would be a good thing.  I think having `CLICOLOR` equal `2` instead of `CLICOLOR_FORCE` would make things easier by just having one consistent name to deal with.

Of course, all of the hard work is going to be patching all of the software that already supports `NO_COLOR` to support `CLICOLOR` instead.

**Comment by FedericoCeratto** [comment]
While I've never felt the need for NO_COLOR, it is annoying how application need configuration to use dark-on-light vs light-on-dark schemes. It would be nice to have a global switch for that as well.
Even better if both CLI and graphical application could switch at runtime. It would help when using laptops indoors, outdoors, at daytime and nighttime.

**Comment by jhasse** [comment]
Why did you close this issue? :(

**Comment by ssbarnea** [comment]
A very good question. If we are about to standardize we need to consolidate approaches, joining efforts.

**Comment by HorlogeSkynet** [comment]
Just for your information, I've intended to propose [an implementation _doing_ its best to honor both](https://github.com/HorlogeSkynet/archey4/blob/c258b756621752f10a09566c297cb829dd25066f/archey/colors.py#L47).

**Comment by jhasse** [comment]
I've went ahead and combined the two: https://github.com/jhasse/clicolors/pull/12 Looking for comments :)
