### ISSUE TITLE
Document --color / FORCE_COLOR=1 for various nodejs libraries and CLI

### ISSUE THREAD

**Issue by osteele** [jcs/no_color#29]
The Chalk npm package <https://github.com/chalk/chalk> uses `--color` (on the command line), or the `FORCE_COLOR=0` environment variable, to disable color. This behavior is therefore inherited by other packages, and CLI tools, that use this package.

Chalk is used by the popular nodejs packages grunt, gulp, jest, webpack, yarn, yeoman, as well as [~23K others](https://www.npmjs.com/browse/depended/chalk).

I started to create a PR that added a entries for `chalk` and `yarn` to the "Disabling color in software not supporting NO_COLOR", but then I looked at what other packages had the same instructions as these two for disabling color, and it looked like listing them would get out of hand.

Some alternatives:

1. Hand-pick a few of the most popular packages (say, the ones in the second paragraph of this issue), and add entries for them to "Disabling color in software not supporting NO_COLOR", with the text "`--color` or `export FORCE_COLOR=0`".
2. Add a new section "Software supporting --no-color / FORCE_COLOR to disable default color output"
3. Add a general note that many other softwares, not listed in this site, support `--no-color` / `FORCE_COLOR` instead of `NO_COLOR`
4. Propose that Chalk adopt `NO_COLOR`. (A proposal would need to specify the interaction of `FORCE_COLOR=1` and `NO_COLOR`, when both are present.)

**Comment by JohnRGee** [comment]
Regarding (4), it has been proposed for Chalk and was rejected:
<https://github.com/chalk/supports-color/issues/74>

**Comment by jcs** [comment]
I choose the first option.
