### ISSUE TITLE
Enforce a generic env

### ISSUE THREAD

**Issue by BridgeAR** [jcs/no_color#49]
This is related to e.g., #29 and #28:

Currently there is a manifest to support the `NO_COLOR` env but instead of having a specific environment variable to prohibit colors, would it not be significantly better to have a single environment that is suggested to use which is able to control color support altogether i.e., deactivate colors and add color support depending on the value. Currently multiple environment variables could be set depending on the terminal / application while one wants to prohibit colors and the other tries to enforce a color. Having a single environment variable would overcome that problem.

I believe there should be a single standard instead of having multiple ones which is currently the case. This is also somewhat related to e.g., https://github.com/termstandard/colors/ (which is a newly created repo from https://gist.github.com/XVilka/8346728).

**Comment by jcs** [comment]
Why did you open a new issue just to comment on two existing issues?

**Comment by BridgeAR** [comment]
@jcs neither wants exactly what I suggest. So it did seem to be a separate issue. Shall I add my comment to one of the existing ones? If so, please suggest to which one.
