### ISSUE TITLE
Patched to add NO_COLOR and FORCE_COLOR for python colorama based tools

### ISSUE THREAD

**Issue by jhol** [jcs/no_color#62]
Just by coincidence, I've been working on a patch for python's colorama library, that adds `FORCE_COLOR` and `NO_COLOR` options.

https://github.com/tartley/colorama/pull/230

I submitted this a few days ago. Then by chance I found a link to this project on Mastadon.

Hopefully I can get my PR merged before too long.

**Comment by jcs** [comment]
Please submit a PR when it's been merged, thanks.
